### ISSUE TITLE
Sao phải là Dom -> Wasm , vì dù porting và tracking tốt thì vẫn khó sync Dom và Virtual Dom

### ISSUE THREAD

**Issue by junotran** [15110123/Blazor-Utils#1]
Dear Tân. Tư duy của bạn rất tuyệt vời, sẽ là 1 đóng góp lớn cho cộng đồng khi bạn tạo ra 1 bộ framework tiện lợi như vậy. Tuy nhiên mình có vài ý trao đổi xem sao.
- 1/ Sức mạnh và cái hay của Blazor (Wasm) là virtual dom chứ ko theo cách tuong tác trực tiếp với dom như các nèn js cũ, bản thân từ Dan R hay Stev cũng khuyên giai quyet moi chuyen theo huong đó, vậy nên thay vì bạn đang cố porting JQuery -> Blazor sao không phải là RERENDER DOM --> như vậy đúng với ý đồ team core Blazor luôn đấy, chắc chắn hướng đó sẽ được nền tảng hỗ trợ nhiều.
-2 / Khi ta đã control UI tốt, cách đây vài năm tôi có nghe và tìm hiểu về khái niệm Dynamic UI Semantic. Ngắn gọn dễ hiểu là tự cổ chí kim thì luôn là Human phải đi tìm hiểu để sử dụng software, chứ software có lẽ chưa bao giờ biết "auto transform" để phù hợp nhất với "kẻ đang dùng mình". Ngoài ra con nhieu cau chuyện thú vị khác  mà cơ hội sẽ rộng lớn ở thời điểm bản lề transform này. Hi vọng sớm contact đc với bạn

**Comment by RoggerTan** [comment]
Chào bạn junotran. Thực ra đây là lần đầu tiên mình nhận được các message góp ý bằng tiếng Việt, vì description, blogs,... của mình toàn dùng tiếng Anh nên mình rất vui. Càng vui hơn khi ở Việt Nam, có người giống như mình, lại hứng thú với Blazor sớm như vậy. 
1. WASM thực tế là vẫn chưa thể tác động đến DOM một cách native được nhưng rất có thể sẽ được hỗ trợ sớm trên Chrome hay các trình duyệt phổ biến khác trong tương lai. Vậy nên, lúc này, nếu gặp vấn đề chẳng hạn như "làm thế nào để thay đổi title của trang web trong Blazor?", không biết bạn sẽ làm thế nào? Nếu jQuery tồn tại và có thể gõ trong môi trường Razor (cshtml) thì mọi chuyện quá đơn giản: $("head title").text("New title") chẳng hạn. 
Nhưng nếu điều này không xảy ra, mình nghĩ bạn phải dùng Js song song C# mới giải quyết được. Nếu bạn có thể giải quyết vấn đề mình nêu ra nhanh hơn, ổn hơn thì hướng dẫn mình nhé. Có thể mình đã quên thủ thuật gì đó cũng nên. ^^
Thực ra việc này có thể khiến bạn nhớ đến vấn đề jQuery được dùng trong React.Js. Đã có nhiều cuộc tranh cãi nảy ra, nhưng rõ ràng không thiếu dự án chấp nhận sự kết hợp này, và Facebook cũng nói rằng lập trình viên có thể dùng "nếu trong tính huống bắt buộc phải làm vậy". Nhưng điểm khác biệt ở đây là ngôn ngữ lập trình. Sẽ không hay lắm nếu vừa phải viết Js và C# cho phần logic của một trang web chỉ để thay đổi title, đúng không? 
Mình cũng đang tiến hành thực hiện dự án đánh giá vai trò của Blazor Utils. Dự án giúp đánh giá và vạch ra các trường hợp nếu sử dụng Blazor Utils sẽ hợp lý hơn. Sẽ hơi lâu do mình đang là sinh viên năm 4, còn phải bận học và làm khóa luận, nhưng mong mọi thứ sẽ ổn. 
2. Khái niệm Dynamic UI Semantic thú vị thật. Khi mình thấy UI Semantic thì lại liên tưởng đến thư viện cùng tên thôi. Bạn có thể chia sẻ cho mình tài liệu về nó được không, vì mình chưa tìm được trên Google nội dung tương tự?

**Comment by junotran** [comment]
Dear Tân. rất vui vì bạn trả lời. Về vấn đề bạn nêu mình đã xử lý xong trên framework mình đang dev.
1. Vấn đề comunity giữa các component mình chia làm 2 dạng : comunity liên quan tới data only và comunity liên quan UI, trong đó mình thiết kế toàn bộ action tác động tới UI sẽ do 1 serice master được Dependen Inject đóng vai trò quản lý + kênh liên lạc chung của all components. Mình truoc đây cũng đi theo hướng lôi những thứ từ Js lên nhưng sau phát hiện ra không thể ổn được vì WASM hiển thị mọi thứ là Virtual DOM, vốn dĩ sẽ luôn tồn tại sự bất đồng bộ hoặc vấn đề nào đó giữa việc thông DOM thật với Virtual, do vậy mình đổi hướng, làm theo cách WASM và team Blazor họ đang làm : Listen DOM thật và Rerender trên DOM ảo --> như vậy bạn full control với những gì hiển thị , cái service UI mà mình nhắc tới đóng vai trò quản lý mọi elements đó. JQuery chưa phải điều sung sướng nếu làm kiểu này, bạn có hình dung ra thay vì đám selectors của JQuery, giờ mình điểu khiển, truy cập DOM bằng ... LINQ
Ngoài ra trong quá trình dev chắc bạn cũng phát hiện 1 thiếu xot của nền tảng : đó là mối quan hệ giữa component cha và các component con là không có, trong khi nhiều ngữ cảnh ta cần điều đó, đưa mọi thứ về Object Oriented Base + Linq ta sẽ perfect bài toán này.
Tân cho mình xin contact FB hoặc kênh nào đó để tiện liên lạc

**Comment by RoggerTan** [comment]
Facebook: [https://www.facebook.com/roggertanvus](https://www.facebook.com/roggertanvus)
Nếu tên FB của bạn không phải junotran thì nhắn tin Messenger sau khi kết bạn nha. Mình không kết bạn với người lạ trên mạng xã hội này. 
Bạn khiến tôi tò mò thật. Có lẽ bộ framework bạn đang phát triển là dạng closed source nên mình không thấy trong GitHub của bạn. Mình sẽ suy nghĩ nghiêm túc về vấn đề này. LINQ cũng là một giải pháp hay. Nhưng liệu team Blazor sau này có sử dụng ý tưởng như thế không? Cách đây khoảng nửa năm, mình đọc được bài blog, đại khái là khi ra phiên bản production, Blazor có thể tương tác với DOM như các đối tượng .NET thuần túy. Mình cũng rất tò mò rằng sau này ta sẽ truy vấn các đối tượng đó ra như thế nào. 
Do khá eo hẹp thời gian, mình sẽ đọc kĩ và suy nghĩ thêm về hồi đáp của bạn. Cảm ơn bạn nhé!
